# Generated by Django 2.0.7 on 2025-03-17 00:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('ctitle', models.CharField(max_length=20, verbose_name='Product Name')),
                ('cusername', models.CharField(max_length=20, verbose_name='Commenter Nickname')),
                ('cusername1', models.CharField(max_length=20, verbose_name='Replier Nickname')),
                ('ccontent_chart', tinymce.models.HTMLField(max_length=200, verbose_name='Comment Reply')),
                ('date_publish', models.DateTimeField(default=datetime.datetime.now, verbose_name='Published Date')),
            ],
            options={
                'verbose_name': 'Comment Reply',
                'verbose_name_plural': 'Comment Reply',
            },
        ),
        migrations.CreateModel(
            name='GoodsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('ctitle', models.CharField(max_length=20, verbose_name='Product Name')),
                ('cpic', models.ImageField(blank=True, null=True, upload_to='df_goods/image/%Y/%m', verbose_name='Uploaded Image')),
                ('cusername', models.CharField(max_length=20, verbose_name='Buyer Nickname')),
                ('clogo', models.CharField(default=None, max_length=200, verbose_name='Buyer Avatar')),
                ('cuser_content', tinymce.models.HTMLField(max_length=200, verbose_name='User Comment')),
                ('date_publish', models.DateTimeField(default=datetime.datetime.now, verbose_name='Published Date')),
            ],
            options={
                'verbose_name': 'Product Comment',
                'verbose_name_plural': 'Product Comment',
            },
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('gtitle', models.CharField(max_length=20, unique=True, verbose_name='Product Name')),
                ('gpic', models.ImageField(blank=True, null=True, upload_to='df_goods/image/%Y/%m', verbose_name='Product Image')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Product Price')),
                ('gunit', models.CharField(max_length=20, verbose_name='Seller Nickname')),
                ('gclick', models.IntegerField(default=0, verbose_name='Click Count')),
                ('gjianjie', models.CharField(max_length=200, verbose_name='Description')),
                ('gkucun', models.IntegerField(default=0, verbose_name='Stock')),
                ('gcontent', tinymce.models.HTMLField(max_length=200, verbose_name='Details')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('ttitle', models.CharField(max_length=20, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Type',
            },
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.TypeInfo', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='goodscontent',
            name='cgoodsname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo', verbose_name='Related Product'),
        ),
        migrations.AddField(
            model_name='contentchart',
            name='ccontent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsContent', verbose_name='Comment ID'),
        ),
    ]
